name: CI

on:
  push:
    branches-ignore: [gh-pages]
    paths-ignore: ["*.md", "*.yml", "*.yaml"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install node_modules
        run: yarn install
      - name: Build NextJS
        run: yarn build
        env:
          NEXT_PUBLIC_USER_ID:  ${{secrets.NEXT_PUBLIC_USER_ID}}
          NEXT_PUBLIC_SERVICE_ID: ${{secrets.NEXT_PUBLIC_SERVICE_ID}}
          NEXT_PUBLIC_TEMPLATE_ID: ${{secrets.NEXT_PUBLIC_TEMPLATE_ID}